### ISSUE TITLE
Multiple consumptions of batchUpdates fail

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#123]
E.g. on flink
```
java.lang.RuntimeException: No data sinks have been created yet. A program needs at least one sink that consumes data. Examples are writing the data set or printing it.
	at org.apache.flink.api.java.ExecutionEnvironment.createProgramPlan(ExecutionEnvironment.java:948)
	at org.apache.flink.api.java.ExecutionEnvironment.createProgramPlan(ExecutionEnvironment.java:926)
	at org.apache.flink.api.java.LocalEnvironment.execute(LocalEnvironment.java:85)
	at org.apache.beam.runners.flink.FlinkPipelineExecutionEnvironment.executePipeline(FlinkPipelineExecutionEnvironment.java:139)
	at org.apache.beam.runners.flink.FlinkRunner.run(FlinkRunner.java:115)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:315)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:301)
	at cz.o2.proxima.beam.tools.groovy.BeamStream.lambda$forEachRemote$10(BeamStream.java:383)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pipeline-start-thread" java.lang.RuntimeException: Pipeline execution failed
	at org.apache.beam.runners.flink.FlinkRunner.run(FlinkRunner.java:118)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:315)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:301)
	at cz.o2.proxima.beam.tools.groovy.BeamStream.lambda$forEachRemote$10(BeamStream.java:383)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: No data sinks have been created yet. A program needs at least one sink that consumes data. Examples are writing the data set or printing it.
	at org.apache.flink.api.java.ExecutionEnvironment.createProgramPlan(ExecutionEnvironment.java:948)
	at org.apache.flink.api.java.ExecutionEnvironment.createProgramPlan(ExecutionEnvironment.java:926)
	at org.apache.flink.api.java.LocalEnvironment.execute(LocalEnvironment.java:85)
	at org.apache.beam.runners.flink.FlinkPipelineExecutionEnvironment.executePipeline(FlinkPipelineExecutionEnvironment.java:139)
	at org.apache.beam.runners.flink.FlinkRunner.run(FlinkRunner.java:115)
```

**Comment by je-ik** [comment]
Closed via datadrivencz#254
