### ISSUE TITLE
KafkaLogReader can seek to negative offsets

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#140]
```
2020-03-05 16:20:53,744 ERROR cz.o2.proxima.direct.kafka.KafkaLogReader                     - Error processing consumer null
java.lang.IllegalArgumentException: seek offset must not be a negative number
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.KafkaConsumer.seek(KafkaConsumer.java:1560)
	at cz.o2.proxima.direct.kafka.Utils.lambda$seekToOffsets$0(Utils.java:50)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at cz.o2.proxima.direct.kafka.Utils.seekToOffsets(Utils.java:46)
	at cz.o2.proxima.direct.kafka.KafkaLogReader.createConsumer(KafkaLogReader.java:633)
	at cz.o2.proxima.direct.kafka.KafkaLogReader.lambda$submitConsumerWithObserver$4(KafkaLogReader.java:342)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by je-ik** [comment]
Closed via datadrivencz#300
