### ISSUE TITLE
leftOuterJoin fails with CoderException

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#145]
```
Caused by: org.apache.beam.sdk.coders.CoderException: Cannot encode a null value.
        at org.apache.beam.sdk.extensions.kryo.KryoCoder.encode(KryoCoder.java:197)
        at cz.o2.proxima.beam.core.io.PairCoder.encode(PairCoder.java:59)
        at cz.o2.proxima.beam.core.io.PairCoder.encode(PairCoder.java:31)
        at org.apache.beam.sdk.coders.Coder.encode(Coder.java:136)
        at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.encode(WindowedValue.java:590)
        at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.encode(WindowedValue.java:581)
        at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.encode(WindowedValue.java:541)
        at org.apache.beam.runners.flink.translation.types.CoderTypeSerializer.serialize(CoderTypeSerializer.java:105)
        at org.apache.flink.runtime.plugable.SerializationDelegate.write(SerializationDelegate.java:54)
```

**Comment by je-ik** [comment]
Fixed via datadrivencz#346
