### ISSUE TITLE
StackOverflow when deserializing Repository

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#167]
```
java.lang.StackOverflowError
	at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
	at java.io.File.exists(File.java:821)
	at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java:1377)
	at sun.misc.URLClassPath$FileLoader.findResource(URLClassPath.java:1344)
	at sun.misc.URLClassPath$1.next(URLClassPath.java:277)
	at sun.misc.URLClassPath$1.hasMoreElements(URLClassPath.java:287)
	at java.net.URLClassLoader$3$1.run(URLClassLoader.java:604)
	at java.net.URLClassLoader$3$1.run(URLClassLoader.java:602)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader$3.next(URLClassLoader.java:601)
	at java.net.URLClassLoader$3.hasMoreElements(URLClassLoader.java:626)
	at sun.misc.CompoundEnumeration.next(CompoundEnumeration.java:45)
	at sun.misc.CompoundEnumeration.hasMoreElements(CompoundEnumeration.java:54)
	at org.apache.flink.util.ChildFirstClassLoader.getResources(ChildFirstClassLoader.java:107)
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:348)
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at cz.o2.proxima.repository.ConfigRepository.getDataOperatorForDelegate(ConfigRepository.java:1916)
	at cz.o2.proxima.repository.ConfigRepository.setupTransform(ConfigRepository.java:811)
	at cz.o2.proxima.repository.ConfigRepository.lambda$setupTransforms$1(ConfigRepository.java:374)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at cz.o2.proxima.repository.ConfigRepository.setupTransforms(ConfigRepository.java:371)
	at cz.o2.proxima.repository.ConfigRepository.reloadConfig(ConfigRepository.java:354)
	at cz.o2.proxima.repository.ConfigRepository.<init>(ConfigRepository.java:305)
	at cz.o2.proxima.repository.ConfigRepository.<init>(ConfigRepository.java:73)
	at cz.o2.proxima.repository.ConfigRepository$Builder.build(ConfigRepository.java:197)
	at cz.o2.proxima.repository.ConfigRepository.ofCached(ConfigRepository.java:111)
	at cz.o2.proxima.repository.RepositoryFactory$Compressed.applyWithFactory(RepositoryFactory.java:53)
	at cz.o2.proxima.repository.RepositoryFactory$VersionedCaching.apply(RepositoryFactory.java:92)
	at cz.o2.proxima.direct.core.DirectAttributeFamilyDescriptor.repo(DirectAttributeFamilyDescriptor.java:232)
	at cz.o2.proxima.direct.core.DirectAttributeFamilyDescriptor.writer(DirectAttributeFamilyDescriptor.java:125)
	at cz.o2.proxima.direct.core.DirectAttributeFamilyDescriptor.getWriter(DirectAttributeFamilyDescriptor.java:118)
	at java.util.Optional.flatMap(Optional.java:241)
	at cz.o2.proxima.direct.core.DirectAttributeFamilyProxyDescriptor.getWriter(DirectAttributeFamilyProxyDescriptor.java:171)
	at cz.o2.proxima.direct.core.DirectAttributeFamilyProxyDescriptor.<init>(DirectAttributeFamilyProxyDescriptor.java:157)
	at cz.o2.proxima.direct.core.DirectAttributeFamilyProxyDescriptor.of(DirectAttributeFamilyProxyDescriptor.java:64)
	at cz.o2.proxima.direct.core.DirectDataOperator.addResolvedFamily(DirectDataOperator.java:168)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at cz.o2.proxima.direct.core.DirectDataOperator.reload(DirectDataOperator.java:105)
	at cz.o2.proxima.direct.core.DirectDataOperator.<init>(DirectDataOperator.java:87)
	at cz.o2.proxima.direct.core.DirectDataOperatorFactory.create(DirectDataOperatorFactory.java:32)
	at cz.o2.proxima.direct.core.DirectDataOperatorFactory.create(DirectDataOperatorFactory.java:23)
	at cz.o2.proxima.repository.Repository.lambda$asDataOperator$4(Repository.java:232)
	at java.util.Optional.map(Optional.java:215)
	at cz.o2.proxima.repository.Repository.asDataOperator(Repository.java:230)
	at cz.o2.proxima.repository.Repository.getOrCreateOperator(Repository.java:259)
	at cz.o2.proxima.beam.direct.io.DirectDataAccessorFactory.setup(DirectDataAccessorFactory.java:42)
	at cz.o2.proxima.storage.internal.DataAccessorLoader.lambda$new$0(DataAccessorLoader.java:51)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at cz.o2.proxima.storage.internal.DataAccessorLoader.<init>(DataAccessorLoader.java:51)
	at cz.o2.proxima.storage.internal.DataAccessorLoader.of(DataAccessorLoader.java:44)
	at cz.o2.proxima.beam.core.BeamDataOperator.<init>(BeamDataOperator.java:126)
	at cz.o2.proxima.beam.core.BeamDataOperatorFactory.create(BeamDataOperatorFactory.java:37)
	at cz.o2.proxima.beam.core.BeamDataOperatorFactory.create(BeamDataOperatorFactory.java:23)
	at cz.o2.proxima.repository.ConfigRepository.lambda$getDataOperatorForDelegate$95(ConfigRepository.java:1923)
	at java.util.Optional.orElseGet(Optional.java:267)
	at cz.o2.proxima.repository.ConfigRepository.getDataOperatorForDelegate(ConfigRepository.java:1923)
	at cz.o2.proxima.repository.ConfigRepository.setupTransform(ConfigRepository.java:811)
	at cz.o2.proxima.repository.ConfigRepository.lambda$setupTransforms$1(ConfigRepository.java:374)
```

**Comment by je-ik** [comment]
Closed via datadrivencz#419
