### ISSUE TITLE
ConcurrentModiifcationException when closing ZKGlobalWatermarkTracker

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#188]
```
2021-01-04 15:47:42 ERROR ClientCnxn:589 - Error while calling watcher
java.lang.RuntimeException: java.util.ConcurrentModificationException: Tracker ZKGlobalWatermarkTracker{trackerName=cz.o2.smartbox.tools, zkConnectString=zk-cs:2181, parentNode=/watermark-limiter/, sessionTimeout=60000, maxAcceptableUpdateMs=180000} has already been closed.
	at cz.o2.proxima.util.ExceptionUtils.ignoringInterrupted(ExceptionUtils.java:141)
	at cz.o2.proxima.utils.zookeeper.ZKGlobalWatermarkTracker.handleWatchOnParentNode(ZKGlobalWatermarkTracker.java:577)
	at cz.o2.proxima.utils.zookeeper.ZKGlobalWatermarkTracker.watchParentNode(ZKGlobalWatermarkTracker.java:569)
	at cz.o2.proxima.utils.zookeeper.ZKGlobalWatermarkTracker.lambda$getWatcher$19(ZKGlobalWatermarkTracker.java:560)
	at cz.o2.proxima.utils.zookeeper.org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:587)
	at cz.o2.proxima.utils.zookeeper.org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:562)
Caused by: java.util.ConcurrentModificationException: Tracker ZKGlobalWatermarkTracker{trackerName=cz.o2.smartbox.tools, zkConnectString=zk-cs:2181, parentNode=/watermark-limiter/, sessionTimeout=60000, maxAcceptableUpdateMs=180000} has already been closed.
	at cz.o2.proxima.utils.zookeeper.ZKGlobalWatermarkTracker.client(ZKGlobalWatermarkTracker.java:529)
	at cz.o2.proxima.utils.zookeeper.ZKGlobalWatermarkTracker.lambda$handleWatchOnChildNode$21(ZKGlobalWatermarkTracker.java:600)
	at cz.o2.proxima.utils.zookeeper.ZKGlobalWatermarkTracker.handleWatchOnChildNode(ZKGlobalWatermarkTracker.java:601)
	at cz.o2.proxima.utils.zookeeper.ZKGlobalWatermarkTracker.lambda$createWatchForChildren$16(ZKGlobalWatermarkTracker.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at cz.o2.proxima.utils.zookeeper.ZKGlobalWatermarkTracker.createWatchForChildren(ZKGlobalWatermarkTracker.java:438)
	at cz.o2.proxima.utils.zookeeper.ZKGlobalWatermarkTracker.lambda$handleWatchOnParentNode$c5b2a3c$1(ZKGlobalWatermarkTracker.java:577)
	at cz.o2.proxima.util.ExceptionUtils.ignoringInterrupted(ExceptionUtils.java:135)
	... 5 more
```

**Comment by je-ik** [comment]
Closed via datadrivencz#485
