### ISSUE TITLE
Validate exceptions thrown on misconfiguration

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#19]
When a miscofiguration occurs, we need to provide user with descriptive exception explaining the problem. Currently, when using `type: primary` for storage without online writing capability, we get
```
Exception in thread "main" java.lang.ClassCastException: cz.o2.proxima.storage.hdfs.HdfsDataAccessor cannot be cast to cz.o2.proxima.storage.OnlineAttributeWriter
   at cz.o2.proxima.storage.AttributeWriterBase.online(AttributeWriterBase.java:47)
   at cz.o2.proxima.repository.Repository.lambda$readAttributeFamilies$17(Repository.java:553)
   at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
   at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
   at cz.o2.proxima.repository.Repository.readAttributeFamilies(Repository.java:543)
   at cz.o2.proxima.repository.Repository.<init>(Repository.java:242)
   at cz.o2.proxima.repository.Repository.<init>(Repository.java:58)
   at cz.o2.proxima.repository.Repository$Builder.build(Repository.java:120)
   at cz.o2.proxima.repository.Repository.of(Repository.java:67)
   at cz.o2.proxima.server.IngestServer.<init>(IngestServer.java:440)
   at cz.o2.proxima.server.IngestServer.main(IngestServer.java:84)
```
The correct explanation would be more like "Do not use bulk storages for primary storage".

**Comment by je-ik** [comment]
Obsolete.
