### ISSUE TITLE
Race between creating and using PubSub subscription

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#197]
```
Exception in thread "pipeline-start-thread" java.lang.RuntimeException: Pipeline execution failed
	at org.apache.beam.runners.flink.FlinkRunner.run(FlinkRunner.java:100)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:322)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:308)
	at cz.o2.proxima.beam.tools.groovy.BeamStream.lambda$runPipeline$10(BeamStream.java:412)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:147)
	at org.apache.flink.client.program.PerJobMiniClusterFactory$PerJobMiniClusterJobClient.lambda$getJobExecutionResult$2(PerJobMiniClusterFactory.java:186)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.apache.flink.runtime.rpc.akka.AkkaInvocationHandler.lambda$invokeRpc$0(AkkaInvocationHandler.java:229)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.apache.flink.runtime.concurrent.FutureUtils$1.onComplete(FutureUtils.java:892)
	at akka.dispatch.OnComplete.internal(Future.scala:264)
	at akka.dispatch.OnComplete.internal(Future.scala:261)
	at akka.dispatch.japi$CallbackBridge.apply(Future.scala:191)
	at akka.dispatch.japi$CallbackBridge.apply(Future.scala:188)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at org.apache.flink.runtime.concurrent.Executors$DirectExecutionContext.execute(Executors.java:74)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:44)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:252)
	at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:572)
	at akka.pattern.PipeToSupport$PipeableFuture$$anonfun$pipeTo$1.applyOrElse(PipeToSupport.scala:22)
	at akka.pattern.PipeToSupport$PipeableFuture$$anonfun$pipeTo$1.applyOrElse(PipeToSupport.scala:21)
	at scala.concurrent.Future$$anonfun$andThen$1.apply(Future.scala:436)
	at scala.concurrent.Future$$anonfun$andThen$1.apply(Future.scala:435)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:116)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:78)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:192)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:185)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:179)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:590)
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:384)
	at jdk.internal.reflect.GeneratedMethodAccessor124.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:286)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:201)
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:74)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:154)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	... 4 more
Caused by: org.apache.beam.sdk.util.UserCodeException: java.lang.RuntimeException: cz.o2.proxima.pubsub.shaded.com.google.api.gax.rpc.InvalidArgumentException: cz.o2.proxima.pubsub.shaded.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid resource name given (name=projects/o2-smartbox-test-make21/subscriptions/36fa3010-1d23-48eb-9ea5-b19b74ee1599). Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information.
	at org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:39)
	at cz.o2.proxima.beam.direct.io.CommitLogRead$UnboundedCommitLogReadFn$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.core.OutputAndTimeBoundedSplittableProcessElementInvoker.invokeProcessElement(OutputAndTimeBoundedSplittableProcessElementInvoker.java:123)
	at org.apache.beam.runners.core.SplittableParDoViaKeyedWorkItems$ProcessFn.processElement(SplittableParDoViaKeyedWorkItems.java:523)
	at org.apache.beam.runners.core.SplittableParDoViaKeyedWorkItems$ProcessFn$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:232)
	at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:188)
	at org.apache.beam.runners.flink.metrics.DoFnRunnerWithMetricsUpdate.processElement(DoFnRunnerWithMetricsUpdate.java:62)
	at org.apache.beam.runners.flink.translation.wrappers.streaming.DoFnOperator.processElement(DoFnOperator.java:645)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:161)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.processElement(StreamTaskNetworkInput.java:178)
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.emitNext(StreamTaskNetworkInput.java:153)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:67)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:351)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:185)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:569)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:534)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:546)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: cz.o2.proxima.pubsub.shaded.com.google.api.gax.rpc.InvalidArgumentException: cz.o2.proxima.pubsub.shaded.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid resource name given (name=projects/o2-smartbox-test-make21/subscriptions/36fa3010-1d23-48eb-9ea5-b19b74ee1599). Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information.
	at cz.o2.proxima.direct.pubsub.PubSubReader.newSubscriber(PubSubReader.java:414)
	at cz.o2.proxima.direct.pubsub.PubSubReader.consume(PubSubReader.java:529)
	at cz.o2.proxima.direct.pubsub.PubSubReader.observeBulk(PubSubReader.java:283)
	at cz.o2.proxima.direct.pubsub.PubSubReader.observeBulkWithMinWatermark(PubSubReader.java:379)
	at cz.o2.proxima.direct.pubsub.PubSubReader.observeBulkPartitions(PubSubReader.java:367)
	at cz.o2.proxima.direct.commitlog.CommitLogReader.observeBulkPartitions(CommitLogReader.java:212)
	at cz.o2.proxima.beam.direct.io.CommitLogRead$UnboundedCommitLogReadFn.observeBulkPartitions(CommitLogRead.java:301)
	at cz.o2.proxima.beam.direct.io.CommitLogRead$AbstractCommitLogReadFn.startObserve(CommitLogRead.java:444)
	at cz.o2.proxima.beam.direct.io.CommitLogRead$AbstractCommitLogReadFn.process(CommitLogRead.java:361)
	at cz.o2.proxima.beam.direct.io.CommitLogRead$UnboundedCommitLogReadFn.processUnbounded(CommitLogRead.java:236)
Caused by: cz.o2.proxima.pubsub.shaded.com.google.api.gax.rpc.InvalidArgumentException: cz.o2.proxima.pubsub.shaded.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid resource name given (name=projects/o2-smartbox-test-make21/subscriptions/36fa3010-1d23-48eb-9ea5-b19b74ee1599). Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information.
	at cz.o2.proxima.pubsub.shaded.com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:49)
	at cz.o2.proxima.pubsub.shaded.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at cz.o2.proxima.pubsub.shaded.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at cz.o2.proxima.pubsub.shaded.com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at cz.o2.proxima.pubsub.shaded.com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at cz.o2.proxima.pubsub.shaded.com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1015)
	at cz.o2.proxima.pubsub.shaded.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at cz.o2.proxima.pubsub.shaded.com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1137)
	at cz.o2.proxima.pubsub.shaded.com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:957)
	at cz.o2.proxima.pubsub.shaded.com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:748)
	at cz.o2.proxima.pubsub.shaded.io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:515)
	at cz.o2.proxima.pubsub.shaded.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at cz.o2.proxima.pubsub.shaded.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at cz.o2.proxima.pubsub.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at cz.o2.proxima.pubsub.shaded.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at cz.o2.proxima.pubsub.shaded.io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at cz.o2.proxima.pubsub.shaded.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at cz.o2.proxima.pubsub.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at cz.o2.proxima.pubsub.shaded.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at cz.o2.proxima.pubsub.shaded.io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at cz.o2.proxima.pubsub.shaded.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at cz.o2.proxima.pubsub.shaded.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at cz.o2.proxima.pubsub.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at cz.o2.proxima.pubsub.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at cz.o2.proxima.pubsub.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
	at cz.o2.proxima.pubsub.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
	at cz.o2.proxima.pubsub.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at cz.o2.proxima.pubsub.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: cz.o2.proxima.pubsub.shaded.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid resource name given (name=projects/o2-smartbox-test-make21/subscriptions/36fa3010-1d23-48eb-9ea5-b19b74ee1599). Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information.
	at cz.o2.proxima.pubsub.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	... 23 more
```

**Comment by je-ik** [comment]
Closed via datadrivencz#497
