### ISSUE TITLE
Exception from io-kafka

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#203]
```
java.lang.IllegalStateException: No current assignment for partition pexeso_events-7
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.internals.SubscriptionState.assignedState(SubscriptionState.java:368)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.internals.SubscriptionState.lambda$requestOffsetReset$3(SubscriptionState.java:615)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.internals.SubscriptionState.requestOffsetReset(SubscriptionState.java:613)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.KafkaConsumer.seekToBeginning(KafkaConsumer.java:1659)
	at cz.o2.proxima.direct.kafka.KafkaLogReader.createConsumer(KafkaLogReader.java:709)
	at cz.o2.proxima.direct.kafka.KafkaLogReader.lambda$submitConsumerWithObserver$3(KafkaLogReader.java:379)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-03-01 16:05:03 ERROR LocalCachedPartitionedView:146 - Failed to prefetch data
java.lang.IllegalStateException: No current assignment for partition pexeso_events-7
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.internals.SubscriptionState.assignedState(SubscriptionState.java:368)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.internals.SubscriptionState.lambda$requestOffsetReset$3(SubscriptionState.java:615)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.internals.SubscriptionState.requestOffsetReset(SubscriptionState.java:613)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.KafkaConsumer.seekToBeginning(KafkaConsumer.java:1659)
	at cz.o2.proxima.direct.kafka.KafkaLogReader.createConsumer(KafkaLogReader.java:709)
	at cz.o2.proxima.direct.kafka.KafkaLogReader.lambda$submitConsumerWithObserver$3(KafkaLogReader.java:379)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by je-ik** [comment]
Not related to proxima.
