### ISSUE TITLE
BeamDataOperatorTest.testUnboundedCommitLogConsumptionWithWindowManyMany is flaky

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#231]
```
[ERROR] cz.o2.proxima.beam.core.BeamDataOperatorTest.testUnboundedCommitLogConsumptionWithWindowManyMany  Time elapsed: 17.999 s  <<< ERROR!
org.apache.beam.sdk.Pipeline$PipelineExecutionException: 
java.lang.AssertionError: org.apache.beam.sdk.extensions.euphoria.core.client.operator.CountByKey/org.apache.beam.sdk.extensions.euphoria.core.client.operator.ReduceByKey/combine/Combine.GroupedValues/ParDo(Anonymous)/ParMultiDo(Anonymous).output: 
Expected: iterable over [<KV{, 1000}>, <KV{, 1}>] in any order
     but: Not matched: <KV{, 899}>
	at cz.o2.proxima.beam.core.BeamDataOperatorTest.runPipeline(BeamDataOperatorTest.java:481)
	at cz.o2.proxima.beam.core.BeamDataOperatorTest.validatePCollectionWindowedRead(BeamDataOperatorTest.java:476)
	at cz.o2.proxima.beam.core.BeamDataOperatorTest.testUnboundedCommitLogConsumptionWithWindowManyMany(BeamDataOperatorTest.java:178)
```

**Comment by je-ik** [comment]
Fixed via datadrivencz#574
