### ISSUE TITLE
Flake in TransactionIT

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#255]
```
Error:  Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.784 s <<< FAILURE! - in cz.o2.proxima.direct.transaction.manager.TransactionIT
Error:  cz.o2.proxima.direct.transaction.manager.TransactionIT.testAtomicAmountTransfer  Time elapsed: 1.304 s  <<< FAILURE!
java.lang.AssertionError: expected:<0.0> but was:<398.413113715053>
	at cz.o2.proxima.direct.transaction.manager.TransactionIT.verifyZeroSum(TransactionIT.java:541)
	at cz.o2.proxima.direct.transaction.manager.TransactionIT.testAtomicAmountTransfer(TransactionIT.java:145)

[INFO] Running cz.o2.proxima.direct.transaction.manager.TransactionLogObserverTest
2021-12-13 12:29:42 ERROR TransactionLogObserver:343 - Fatal error processing transactions. Killing self.
java.lang.RuntimeException: error
```

**Comment by je-ik** [comment]
Another occurrence:
```
Error:  cz.o2.proxima.direct.transaction.manager.TransactionIT.testAtomicAmountTransfer  Time elapsed: 1.205 s  <<< FAILURE!
java.lang.AssertionError: expected:<0.0> but was:<852.6306824605598>
	at cz.o2.proxima.direct.transaction.manager.TransactionIT.verifyZeroSum(TransactionIT.java:541)
	at cz.o2.proxima.direct.transaction.manager.TransactionIT.testAtomicAmountTransfer(TransactionIT.java:145)

```
