### ISSUE TITLE
[proxima-beam] IO probably leaks LogObservers

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#332]
```
Caused by: java.lang.OutOfMemoryError: Direct buffer memory. The direct out-of-memory error has occurred. This can mean two things: either job(s) require(s) a larger size of JVM direct memory or there is a direct memory leak. The direct memory can be allocated by user code or some of its dependencies. In this case 'taskmanager.memory.task.off-heap.size' configuration option should be increased. Flink framework and its dependencies also consume the direct memory, mostly for network communication. The most of network memory is managed by Flink and should not result in out-of-memory error. In certain special cases, in particular for jobs with high parallelism, the framework may require more direct memory which is not managed by Flink. In this case 'taskmanager.memory.framework.off-heap.size' configuration option should be increased. If the error persists then there is probably a direct memory leak in user code or some of its dependencies which has to be investigated and fixed. The task executor has to be shutdown...
	at java.base/java.nio.Bits.reserveMemory(Bits.java:175)
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317)
	at java.base/sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:242)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:242)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.common.network.PlaintextTransportLayer.read(PlaintextTransportLayer.java:103)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:118)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:561)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1296)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1237)
	at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1210)
	at cz.o2.proxima.direct.io.kafka.KafkaLogReader.lambda$submitConsumerWithObserver$7(KafkaLogReader.java:426)
```

**Comment by je-ik** [comment]
Probably not related to readers, but writers. BeamStream should use ProximaIO, which should close writers appropriately.
