### ISSUE TITLE
[transactions] IllegalArgumentException

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#337]
```
java.lang.IllegalArgumentException: null
	at cz.o2.proxima.internal.com.google.common.base.Preconditions.checkArgument(Preconditions.java:129) ~[proxima-vendor-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.core.transaction.TransactionResourceManager.createCachedTransaction(TransactionResourceManager.java:803) ~[proxima-direct-core-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.core.transaction.TransactionResourceManager.lambda$getOrCreateCachedTransaction$17(TransactionResourceManager.java:858) ~[proxima-direct-core-0.15-SNAPSHOT.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at cz.o2.proxima.direct.core.transaction.TransactionResourceManager.getOrCreateCachedTransaction(TransactionResourceManager.java:857) ~[proxima-direct-core-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.core.transaction.TransactionResourceManager.lambda$createTransactionUpdateConsumer$cd75872e$1(TransactionResourceManager.java:555) ~[proxima-direct-core-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.core.view.LocalCachedPartitionedView.onCache(LocalCachedPartitionedView.java:121) ~[proxima-direct-core-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.core.view.LocalCachedPartitionedView$1.onNext(LocalCachedPartitionedView.java:155) ~[proxima-direct-core-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.core.view.LocalCachedPartitionedView$1.onNext(LocalCachedPartitionedView.java:142) ~[proxima-direct-core-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.io.kafka.ElementConsumers$BulkConsumer.consumeWithConfirm(ElementConsumers.java:217) ~[proxima-direct-io-kafka-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.io.kafka.KafkaLogReader.lambda$submitConsumerWithObserver$7(KafkaLogReader.java:479) ~[proxima-direct-io-kafka-0.15-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
2024-07-02 15:25:24.772 ERROR LocalCachedPartitionedView - Failed to prefetch data
java.lang.IllegalArgumentException: null
	at cz.o2.proxima.internal.com.google.common.base.Preconditions.checkArgument(Preconditions.java:129) ~[proxima-vendor-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.core.transaction.TransactionResourceManager.createCachedTransaction(TransactionResourceManager.java:803) ~[proxima-direct-core-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.core.transaction.TransactionResourceManager.lambda$getOrCreateCachedTransaction$17(TransactionResourceManager.java:858) ~[proxima-direct-core-0.15-SNAPSHOT.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at cz.o2.proxima.direct.core.transaction.TransactionResourceManager.getOrCreateCachedTransaction(TransactionResourceManager.java:857) ~[proxima-direct-core-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.core.transaction.TransactionResourceManager.lambda$createTransactionUpdateConsumer$cd75872e$1(TransactionResourceManager.java:555) ~[proxima-direct-core-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.core.view.LocalCachedPartitionedView.onCache(LocalCachedPartitionedView.java:121) ~[proxima-direct-core-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.core.view.LocalCachedPartitionedView$1.onNext(LocalCachedPartitionedView.java:155) ~[proxima-direct-core-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.core.view.LocalCachedPartitionedView$1.onNext(LocalCachedPartitionedView.java:142) ~[proxima-direct-core-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.io.kafka.ElementConsumers$BulkConsumer.consumeWithConfirm(ElementConsumers.java:217) ~[proxima-direct-io-kafka-0.15-SNAPSHOT.jar:?]
	at cz.o2.proxima.direct.io.kafka.KafkaLogReader.lambda$submitConsumerWithObserver$7(KafkaLogReader.java:479) ~[proxima-direct-io-kafka-0.15-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
2024-07-02 15:25:24.774 INFO TransactionManagerServer - TransactionManagerServer shutting down.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at cz.o2.proxima.core@0.15-SNAPSHOT/cz.o2.proxima.core.repository.JPMSMain.main(JPMSMain.java:70)
Caused by: java.lang.IllegalStateException: java.lang.IllegalArgumentException
	at cz.o2.proxima.core@0.15-SNAPSHOT/cz.o2.proxima.core.util.ExceptionUtils.rethrowAsIllegalStateException(ExceptionUtils.java:184)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at cz.o2.proxima.direct.core@0.15-SNAPSHOT/cz.o2.proxima.direct.core.view.LocalCachedPartitionedView.assign(LocalCachedPartitionedView.java:208)
	at cz.o2.proxima.direct.core@0.15-SNAPSHOT/cz.o2.proxima.direct.core.transaction.TransactionResourceManager.lambda$runObservations$9(TransactionResourceManager.java:532)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2980)
	at cz.o2.proxima.direct.core@0.15-SNAPSHOT/cz.o2.proxima.direct.core.transaction.TransactionResourceManager.lambda$runObservations$10(TransactionResourceManager.java:527)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at cz.o2.proxima.direct.core@0.15-SNAPSHOT/cz.o2.proxima.direct.core.transaction.TransactionResourceManager.runObservations(TransactionResourceManager.java:514)
	at cz.o2.proxima.direct.transaction.manager@0.15-SNAPSHOT/cz.o2.proxima.direct.transaction.manager.TransactionLogObserver$1.runObservations(TransactionLogObserver.java:212)
	at cz.o2.proxima.direct.transaction.manager@0.15-SNAPSHOT/cz.o2.proxima.direct.transaction.manager.TransactionLogObserver.run(TransactionLogObserver.java:844)
	at cz.o2.proxima.direct.transaction.manager@0.15-SNAPSHOT/cz.o2.proxima.direct.transaction.manager.TransactionManagerServer.run(TransactionManagerServer.java:134)
	at cz.o2.proxima.direct.transaction.manager@0.15-SNAPSHOT/cz.o2.proxima.direct.transaction.manager.TransactionManagerServer.main(TransactionManagerServer.java:65)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 2 more
Caused by: java.lang.IllegalArgumentException
	at cz.o2.proxima.vendor@0.15-SNAPSHOT/cz.o2.proxima.internal.com.google.common.base.Preconditions.checkArgument(Preconditions.java:129)
	at cz.o2.proxima.direct.core@0.15-SNAPSHOT/cz.o2.proxima.direct.core.transaction.TransactionResourceManager.createCachedTransaction(TransactionResourceManager.java:803)
	at cz.o2.proxima.direct.core@0.15-SNAPSHOT/cz.o2.proxima.direct.core.transaction.TransactionResourceManager.lambda$getOrCreateCachedTransaction$17(TransactionResourceManager.java:858)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at cz.o2.proxima.direct.core@0.15-SNAPSHOT/cz.o2.proxima.direct.core.transaction.TransactionResourceManager.getOrCreateCachedTransaction(TransactionResourceManager.java:857)
	at cz.o2.proxima.direct.core@0.15-SNAPSHOT/cz.o2.proxima.direct.core.transaction.TransactionResourceManager.lambda$createTransactionUpdateConsumer$cd75872e$1(TransactionResourceManager.java:555)
	at cz.o2.proxima.direct.core@0.15-SNAPSHOT/cz.o2.proxima.direct.core.view.LocalCachedPartitionedView.onCache(LocalCachedPartitionedView.java:121)
	at cz.o2.proxima.direct.core@0.15-SNAPSHOT/cz.o2.proxima.direct.core.view.LocalCachedPartitionedView$1.onNext(LocalCachedPartitionedView.java:155)
	at cz.o2.proxima.direct.core@0.15-SNAPSHOT/cz.o2.proxima.direct.core.view.LocalCachedPartitionedView$1.onNext(LocalCachedPartitionedView.java:142)
	at cz.o2.proxima.direct.io.kafka@0.15-SNAPSHOT/cz.o2.proxima.direct.io.kafka.ElementConsumers$BulkConsumer.consumeWithConfirm(ElementConsumers.java:217)
	at cz.o2.proxima.direct.io.kafka@0.15-SNAPSHOT/cz.o2.proxima.direct.io.kafka.KafkaLogReader.lambda$submitConsumerWithObserver$7(KafkaLogReader.java:479)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by je-ik** [comment]
Transaction manager was not restarted upon this exception.
