### ISSUE TITLE
PubSubReader: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by je-ik** [O2-Czech-Republic/proxima-platform#86]
At certain conditions the `PubSubReader` might throw following exception:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at cz.o2.proxima.storage.pubsub.PubSubReader.lambda$null$2(PubSubReader.java:197)
	at java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:179)
	at cz.o2.proxima.storage.pubsub.PubSubReader.lambda$null$3cafaa0b$1(PubSubReader.java:181)
	at cz.o2.proxima.storage.commitlog.BulkLogObserver$OffsetCommitter.confirm(BulkLogObserver.java:57)
	at cz.o2.proxima.source.UnboundedStreamSource$1.lambda$commitOffset$0(UnboundedStreamSource.java:143)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at cz.o2.proxima.source.UnboundedStreamSource$1.commitOffset(UnboundedStreamSource.java:143)
	at cz.o2.proxima.source.UnboundedStreamSource$1.commitOffset(UnboundedStreamSource.java:103)
	at cz.seznam.euphoria.executor.local.LocalExecutor$UnboundedPartitionSupplierStream.get(LocalExecutor.java:119)
	at cz.seznam.euphoria.executor.local.LocalExecutor.lambda$execMap$7(LocalExecutor.java:628)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by je-ik** [comment]
Closed via datadrivencz/proxima-platform#67
